// Code generated by "stringer -type=ErrorType,ControlMsg -output types_string.go"; DO NOT EDIT.

package utils

import "strconv"

const _ErrorType_name = "ErrorEOFErrorOverflowErrorInitializeError"

var _ErrorType_index = [...]uint8{0, 5, 13, 26, 41}

func (i ErrorType) String() string {
	if i < 0 || i >= ErrorType(len(_ErrorType_index)-1) {
		return "ErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorType_name[_ErrorType_index[i]:_ErrorType_index[i+1]]
}

const _ControlMsg_name = "CMsgEOFCMsgStarve"

var _ControlMsg_index = [...]uint8{0, 7, 17}

func (i ControlMsg) String() string {
	if i < 0 || i >= ControlMsg(len(_ControlMsg_index)-1) {
		return "ControlMsg(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ControlMsg_name[_ControlMsg_index[i]:_ControlMsg_index[i+1]]
}
